name: 'GH Actions - Release'

on:
  release:
    types:
      - created
      - edited

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: true

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - FROM:     'ubuntu:mantic'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'OFF'
            ARTIFACT_EXT: 'deb'
          - FROM:     'ubuntu:jammy'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'OFF'
            ARTIFACT_EXT: 'deb'
          - FROM:     'ubuntu:focal'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'OFF'
            ARTIFACT_EXT: 'deb'
          # Source tarballs only
          - FROM:     'ubuntu:focal'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'OFF'
            ARTIFACT_EXT: 'tar.[xb]z*'
          - FROM:     'linuxmintd/mint21.1-amd64'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'OFF'
            ARTIFACT_EXT: 'deb'
          - FROM:     'linuxmintd/mint21-amd64'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'OFF'
            ARTIFACT_EXT: 'deb'
          - FROM:     'linuxmintd/mint20-amd64'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'OFF'
            ARTIFACT_EXT: 'deb'
          - FROM:     'debian:bookworm'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'OFF'
            ARTIFACT_EXT: 'deb'
          - FROM:     'debian:bullseye'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'OFF'
            ARTIFACT_EXT: 'deb'
          - FROM:     'opensuse/leap:15.5'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'ON'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'opensuse/leap:15.4'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'ON'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'fedora:40'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'ON'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'fedora:39'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'ON'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'fedora:38'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'ON'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'rockylinux:9.3'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'ON'
            ARTIFACT_EXT: 'rpm'
          #- FROM:     'rockylinux:8.9'
          #  COMPILER: 'clang'
          #  OpenGL_GL_PREFERENCE: 'GLVND'
          #  ENABLE_PIE: 'ON'
          #  ARTIFACT_EXT: 'rpm'

    steps:
      - name: Check out repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f #v4.1.3
        with:
          fetch-depth: 2
          submodules: false

      - name: Extract tag name and short SHA
        shell: bash
        run: |
          echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/} | sed 's/\//_/g')" >> $GITHUB_ENV
          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Test tag name and short SHA
        run: |
          echo "${TAG_NAME}"
          echo "${SHORT_SHA}"

      - name: Run CI
        env:
          FROM:       ${{ matrix.FROM }}
          COMPILER:   ${{ matrix.COMPILER }}
          FLAGS:      '-DOpenGL_GL_PREFERENCE=${{ matrix.OpenGL_GL_PREFERENCE }} -DENABLE_PIE=${{ matrix.ENABLE_PIE }}'
          MY_OS_NAME: linux
          IS_RELEASE: 1
        run: script/cibuild $FLAGS

      - name: Upload the artifacts
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "packages/*.${{ matrix.ARTIFACT_EXT }}"
