name: 'GH Actions - PR'

on: [ pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - FROM:     'ubuntu:hirsute'
            COMPILER: 'gcc'
            FLAGS:    '-DUSE_PYTHON_3=ON'
          - FROM:     'ubuntu:hirsute'
            COMPILER: 'clang'
            FLAGS:    '-DUSE_PYTHON_3=ON'
          - FROM:     'ubuntu:groovy'
            COMPILER: 'gcc'
            FLAGS:    '-DUSE_PYTHON_3=ON'
          - FROM:     'ubuntu:groovy'
            COMPILER: 'clang'
            FLAGS:    '-DUSE_PYTHON_3=ON'
          - FROM:     'ubuntu:focal'
            COMPILER: 'gcc'
            FLAGS:    '-DUSE_PYTHON_3=ON'
          - FROM:     'ubuntu:focal'
            COMPILER: 'clang'
            FLAGS:    '-DUSE_PYTHON_3=ON'
          - FROM:     'ubuntu:bionic'
            COMPILER: 'gcc'
            FLAGS:    '-DUSE_PYTHON_3=ON'
          - FROM:     'ubuntu:bionic'
            COMPILER: 'clang'
            FLAGS:    '-DUSE_PYTHON_3=ON'
          - FROM:     'ubuntu:xenial'
            COMPILER: 'gcc'
            FLAGS:    '-DUSE_PYTHON_3=ON'
          - FROM:     'linuxmintd/mint20-amd64'
            COMPILER: 'clang'
            FLAGS:    '-DUSE_PYTHON_3=ON'
          - FROM:     'debian:bullseye'
            COMPILER: 'clang'
            FLAGS:    '-DUSE_PYTHON_3=ON'
          - FROM:     'debian:buster'
            COMPILER: 'clang'
            FLAGS:    '-DUSE_PYTHON_3=ON'
          - FROM:     'debian:stretch'
            COMPILER: 'gcc'
            FLAGS:    '-DUSE_PYTHON_3=ON'
          - FROM:     'opensuse/leap'
            COMPILER: 'clang'
            FLAGS:    '-DUSE_PYTHON_3=ON'
          - FROM:     'fedora:34'
            COMPILER: 'clang'
            FLAGS:    '-DUSE_PYTHON_3=ON'
          - FROM:     'fedora:33'
            COMPILER: 'clang'
            FLAGS:    '-DUSE_PYTHON_3=ON'
          - FROM:     'fedora:32'
            COMPILER: 'clang'
            FLAGS:    '-DUSE_PYTHON_3=ON'
          - FROM:     'rockylinux/rockylinux'
            COMPILER: 'clang'
            FLAGS:    '-DUSE_PYTHON_3=ON'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
        submodules: false

    # Ensure PRs are built against the PR Head
    # As opposed to the merge commit
    - name: Move to PR HEAD
      run: git checkout HEAD^2
    - name: Run CI
      env:
        FROM:       ${{ matrix.FROM }}
        COMPILER:   ${{ matrix.COMPILER }}
        FLAGS:      ${{ matrix.FLAGS }}
        MY_OS_NAME: linux
        IS_RELEASE: 0
      run: script/cibuild $FLAGS
