name: 'GH Actions - PR'

on: [ pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - FROM:     'ubuntu:hirsute'
            COMPILER: 'gcc'
          - FROM:     'ubuntu:hirsute'
            COMPILER: 'clang'
          - FROM:     'ubuntu:groovy'
            COMPILER: 'gcc'
          - FROM:     'ubuntu:groovy'
            COMPILER: 'clang'
          - FROM:     'ubuntu:focal'
            COMPILER: 'gcc'
          - FROM:     'ubuntu:focal'
            COMPILER: 'clang'
          - FROM:     'ubuntu:bionic'
            COMPILER: 'gcc'
          - FROM:     'ubuntu:bionic'
            COMPILER: 'clang'
          - FROM:     'linuxmintd/mint20-amd64'
            COMPILER: 'clang'
          - FROM:     'debian:bullseye'
            COMPILER: 'clang'
          - FROM:     'debian:buster'
            COMPILER: 'clang'
          - FROM:     'opensuse/leap'
            COMPILER: 'clang'
          - FROM:     'fedora:34'
            COMPILER: 'clang'
          - FROM:     'fedora:33'
            COMPILER: 'clang'
          - FROM:     'fedora:32'
            COMPILER: 'clang'
          - FROM:     'rockylinux/rockylinux'
            COMPILER: 'clang'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
        submodules: false

    # Ensure PRs are built against the PR Head
    # As opposed to the merge commit
    - name: Move to PR HEAD
      run: git checkout HEAD^2

    - name: Build
      env:
        FROM:       ${{ matrix.FROM }}
        COMPILER:   ${{ matrix.COMPILER }}
        FLAGS:      ''
        MY_OS_NAME: linux
        IS_RELEASE: 0
      run: script/cibuild $FLAGS

    - name: Test
      working-directory: ${{github.workspace}}/build
      env:
        GTEST_OUTPUT: xml
        GTEST_COLOR: 1
      run: ctest -VV --debug

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test_results_xml
        path: ${{github.workspace}}/build/test-results/**/*.xml
