name: 'GH Actions - PR'

on: [ pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: true
      matrix:
        include:
          - FROM:     'ubuntu:impish'
            COMPILER: 'gcc'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'ON'
          - FROM:     'ubuntu:impish'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'ON'
          - FROM:     'ubuntu:impish'
            COMPILER: 'gcc'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'OFF'
          - FROM:     'ubuntu:impish'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'OFF'
          - FROM:     'ubuntu:hirsute'
            COMPILER: 'gcc'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'ON'
          - FROM:     'ubuntu:hirsute'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'ON'
          - FROM:     'ubuntu:hirsute'
            COMPILER: 'gcc'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'OFF'
          - FROM:     'ubuntu:hirsute'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'OFF'
          - FROM:     'ubuntu:focal'
            COMPILER: 'gcc'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'ON'
          - FROM:     'ubuntu:focal'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'ON'
          - FROM:     'ubuntu:focal'
            COMPILER: 'gcc'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'OFF'
          - FROM:     'ubuntu:focal'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'OFF'
          - FROM:     'ubuntu:bionic'
            COMPILER: 'gcc'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'ON'
          - FROM:     'ubuntu:bionic'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'ON'
          - FROM:     'ubuntu:bionic'
            COMPILER: 'gcc'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'OFF'
          - FROM:     'ubuntu:bionic'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'OFF'
          - FROM:     'linuxmintd/mint20-amd64'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'ON'
          - FROM:     'linuxmintd/mint20-amd64'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'OFF'
          - FROM:     'debian:bullseye'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'ON'
          - FROM:     'debian:bullseye'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'OFF'
          - FROM:     'debian:buster'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'ON'
          - FROM:     'debian:buster'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'OFF'
          - FROM:     'opensuse/leap'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'ON'
          - FROM:     'opensuse/leap'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'OFF'
          - FROM:     'fedora:35'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'ON'
          - FROM:     'fedora:35'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'OFF'
          - FROM:     'fedora:34'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'ON'
          - FROM:     'fedora:34'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'OFF'
          - FROM:     'rockylinux/rockylinux'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'ON'
          - FROM:     'rockylinux/rockylinux'
            COMPILER: 'clang'
            USE_PYTHON_3: 'ON'
            PREFER_LEGACY_OPENGL: 'OFF'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
        submodules: false

    # Ensure PRs are built against the PR Head
    # As opposed to the merge commit
    - name: Move to PR HEAD
      run: git checkout HEAD^2

    - name: Run CI
      env:
        FROM:       ${{ matrix.FROM }}
        COMPILER:   ${{ matrix.COMPILER }}
        FLAGS:      '-DUSE_PYTHON_3=${{ matrix.USE_PYTHON_3 }} -DVEGA_STRIKE_PREFER_LEGACY_OPENGL=${{ matrix.PREFER_LEGACY_OPENGL }}'
        MY_OS_NAME: linux
        IS_RELEASE: 0
      run: script/cibuild $FLAGS
