name: 'GH Actions - Release'

on:
  release:
    types:
      - created
      - edited

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: true

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - FROM:     'ubuntu:noble'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'OFF'
            ARTIFACT_EXT: 'deb'
          - FROM:     'ubuntu:jammy'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'OFF'
            ARTIFACT_EXT: 'deb'
          # Source tarballs only
          - FROM:     'ubuntu:jammy'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'OFF'
            ARTIFACT_EXT: 'tar.[xb]z*'
          - FROM:     'linuxmintd/mint22-amd64'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'OFF'
            ARTIFACT_EXT: 'deb'
          - FROM:     'linuxmintd/mint21.3-amd64'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'OFF'
            ARTIFACT_EXT: 'deb'
          - FROM:     'linuxmintd/mint21.2-amd64'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'OFF'
            ARTIFACT_EXT: 'deb'
          - FROM:     'linuxmintd/mint21.1-amd64'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'OFF'
            ARTIFACT_EXT: 'deb'
          - FROM:     'linuxmintd/mint21-amd64'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'OFF'
            ARTIFACT_EXT: 'deb'
          - FROM:     'debian:bookworm'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'OFF'
            ARTIFACT_EXT: 'deb'
          - FROM:     'opensuse/leap:15.6'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'ON'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'fedora:41'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'ON'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'fedora:40'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'ON'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'rockylinux:9.5'
            COMPILER: 'gcc'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'ON'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'rockylinux:8.10'
            COMPILER: 'gcc'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ENABLE_PIE: 'ON'
            ARTIFACT_EXT: 'rpm'

    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2
          submodules: false

      - name: Extract tag name and short SHA
        shell: bash
        run: |
          echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/} | sed 's/\//_/g')" >> $GITHUB_ENV
          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Test tag name and short SHA
        run: |
          echo "${TAG_NAME}"
          echo "${SHORT_SHA}"

      - name: Run CI
        env:
          FROM:       ${{ matrix.FROM }}
          COMPILER:   ${{ matrix.COMPILER }}
          FLAGS:      '-DOpenGL_GL_PREFERENCE=${{ matrix.OpenGL_GL_PREFERENCE }} -DENABLE_PIE=${{ matrix.ENABLE_PIE }}'
          MY_OS_NAME: linux
          IS_RELEASE: 1
        run: script/cibuild $FLAGS

      - name: Upload the artifacts
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "packages/*.${{ matrix.ARTIFACT_EXT }}"
