name: 'MacOS-Release'

on:
  release:
    types:
      - created
      - edited

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        os:
          #- macos-11
          - macos-12
        compiler:
          - clang
          - gcc
        homebrew-gl:
          - true
          # - false
        homebrew-al:
          - true
          - false

    steps:

      # The following dependencies are already present within macos-* images:
      # - clang (llvm)
      # - cmake
      # - expat
      # - gcc
      # - git
      # - jpeg
      # - libpng
      # - libvorbis
      # - python
      - name: Install dependencies using homebrew
        run: brew install boost-python3 gtk+3 gtkglext sdl

      # The following Apple-provided libraries are deprecated:
      # * OpenGL as of macOS 10.14
      # * GLUT as of macOS 10.9
      - name: Optionally install homebrewed OpenGL and GLUT
        if: ${{ matrix.homebrew-gl }}
        run: |
          brew install mesa mesa-glu freeglut
          ln -s /usr/local/include/GL /usr/local/include/OpenGL
          ln -s /usr/local/include/GL /usr/local/include/GLUT
        # ln -s /usr/local/lib/libGL.dylib /usr/local/lib/libOpenGL.dylib
        # find /usr/local/lib/ -iname '*gl*.dylib'

      # The Apple-provided OpenAL is deprecated as of macOS 10.15
      - name: Optionally install homebrewed OpenAL
        if: ${{ matrix.homebrew-al }}
        run: brew install openal-soft

      - name: Check out repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f #v4.1.3
        with:
          fetch-depth: 2
          submodules: false

      - name: Extract tag name and short SHA
        shell: bash
        run: |
          echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/} | sed 's/\//_/g')" >> $GITHUB_ENV
          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Test tag name and short SHA
        run: |
          echo "${TAG_NAME}"
          echo "${SHORT_SHA}"

      - name: Build it
        env:
          MY_OS_NAME: macos
          COMPILER:   ${{ matrix.compiler }}
          FLAGS:      -DCMAKE_FIND_FRAMEWORK=LAST
          OPENALDIR:  "/usr/local/opt/openal-soft"
          IS_RELEASE: 1
        run: script/cibuild $FLAGS

      - name: Test
        working-directory: ${{github.workspace}}/build
        env:
          GTEST_OUTPUT: xml
          GTEST_COLOR: 1
        run: ctest -V

      - name: Upload test results
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 #v4.3.3
        if: failure()
        with:
          name: test_results_xml
          path: ${{github.workspace}}/build/test-results/**/*.xml

      #- name: Upload the artifacts
      #  uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 #v4.3.3
      #  with:
      #    args: "packages/*.${{ matrix.ARTIFACT_EXT }}"
